In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("econocausal_dataset_expanded.csv")
df.head()

,user_id,age,income_bracket,urbanicity,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,cart_abandonment_rate,support_tickets_count,email_open_rate,previous_discounts_accepted,discount_offered,purchased,revenue,net_profit
0,30000,56,5,Suburban,18,181.29,20,5,279.4,0.076,1,0.086,2,0,0,0.00,0.00
1,30001,69,4,Suburban,20,172.22,0,9,296.6,0.079,2,0.584,4,30,1,87.88,72.88
2,30002,46,3,Urban,13,60.87,14,4,260.5,0.453,3,0.353,3,10,0,0.00,-5.00
3,30003,32,4,Rural,7,503.36,1,6,293.9,0.513,1,0.578,1,0,1,152.48,152.48
4,30004,60,4,Urban,18,122.62,19,5,455.4,0.354,3,0.513,1,20,0,0.00,-10.00

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      15000 non-null  int64
 1   age                          15000 non-null  int64
 2   income_bracket               15000 non-null  int64
 3   urbanicity                   15000 non-null  object
 4   tenure_months                15000 non-null  int64
 5   historical_spend             15000 non-null  float64
 6   recency_days                 15000 non-null  int64
 7   browsing_frequency           15000 non-null  int64
 8   avg_session_duration_sec     15000 non-null  float64
 9   cart_abandonment_rate        15000 non-null  float64
 10  support_tickets_count        15000 non-null  int64
 11  email_open_rate              15000 non-null  float64
 12  previous_discounts_accepted  15000 non-null  int64
 13  discount_offered             15000 non-null  int64
 14  purchased                    15000 non-null  int64
 15  revenue                      15000 non-null  float64
 16  net_profit                   15000 non-null  float64
dtypes: float64(6), int64(10), object(1)
memory usage: 1.9+ MB

In [10]:
df.shape

(15000, 17)

In [14]:
df.dtypes

user_id                          int64
age                              int64
income_bracket                   int64
urbanicity                      object
tenure_months                    int64
historical_spend               float64
recency_days                     int64
browsing_frequency               int64
avg_session_duration_sec       float64
cart_abandonment_rate          float64
support_tickets_count            int64
email_open_rate                float64
previous_discounts_accepted      int64
discount_offered                 int64
purchased                        int64
revenue                        float64
net_profit                     float64
dtype: object

In [15]:
df.isnull().sum()

user_id                        0
age                            0
income_bracket                 0
urbanicity                     0
tenure_months                  0
historical_spend               0
recency_days                   0
browsing_frequency             0
avg_session_duration_sec       0
cart_abandonment_rate          0
support_tickets_count          0
email_open_rate                0
previous_discounts_accepted    0
discount_offered               0
purchased                      0
revenue                        0
net_profit                     0
dtype: int64

In [16]:
df.describe()

,user_id,age,income_bracket,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,cart_abandonment_rate,support_tickets_count,email_open_rate,previous_discounts_accepted,discount_offered,purchased,revenue,net_profit
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000
mean,37499.500000,43.452667,2.844067,14.033600,149.158207,11.435133,5.001600,300.585987,0.286726,0.799533,0.499903,2.013600,9.999333,0.283867,30.947187,25.94752
std,4330.271354,14.910732,1.103615,3.749712,94.887166,11.914184,2.243851,89.882355,0.160060,0.897069,0.189042,1.095823,9.952551,0.450888,52.053287,52.29849
min,30000.000000,18.000000,1.000000,2.000000,1.620000,0.000000,0.000000,30.000000,0.003000,0.000000,0.025000,0.000000,0.000000,0.000000,0.000000,-15.00000
25%,33749.750000,31.000000,2.000000,11.000000,78.720000,3.000000,3.000000,239.775000,0.160000,0.000000,0.359000,1.000000,0.000000,0.000000,0.000000,-5.00000
50%,37499.500000,43.000000,3.000000,14.000000,129.575000,8.000000,5.000000,301.000000,0.265000,1.000000,0.498000,2.000000,10.000000,0.000000,0.000000,0.00000
75%,41249.250000,56.000000,3.000000,16.000000,198.152500,16.000000,6.000000,359.800000,0.392000,1.000000,0.641000,3.000000,20.000000,1.000000,70.270000,63.12750
max,44999.000000,69.000000,5.000000,31.000000,815.680000,112.000000,16.000000,636.700000,0.890000,6.000000,0.991000,5.000000,30.000000,1.000000,222.560000,222.56000