# Day 1 — Dataset Audit

In [1]:
import pandas as pd 
from pathlib import Path

In [2]:
data_path = Path(
    r"D:\infotact_intern\project_1\EconoCausal\raw_data\econocausal_enriched_synthetic_dataset.csv"
)
data_path.name

'econocausal_enriched_synthetic_dataset.csv'

In [3]:
df=pd.read_csv(data_path)

In [4]:
df.head()

,customer_id,age,income_bracket,urbanicity,region,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,...,days_since_last_campaign,marketing_contact_count_30d,discount_offered,discount_amount,purchased,basket_value_before_discount,revenue,cost_of_goods,marketing_cost,net_profit
0,100001,44,lower_middle,suburban,west,12,5502.94,4,5,168.9,...,23,3,10,91.95,0,919.46,0.00,0.00,4.50,-4.5
1,100002,39,lower_middle,suburban,west,7,4720.72,51,7,111.3,...,52,1,0,0.00,0,1500.40,0.00,0.00,1.50,-1.5
2,100003,26,lower_middle,rural,north,15,4656.31,12,6,343.7,...,3,2,0,0.00,0,453.77,0.00,0.00,3.00,-3.0
3,100004,25,low,rural,east,16,7174.15,13,10,136.4,...,40,2,10,133.99,1,1339.93,1205.94,905.95,136.99,163.0
4,100005,43,low,rural,west,22,2713.23,66,7,146.4,...,48,1,5,44.28,0,885.56,0.00,0.00,1.50,-1.5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   20000 non-null  int64
 1   age                           20000 non-null  int64
 2   income_bracket                20000 non-null  object
 3   urbanicity                    20000 non-null  object
 4   region                        20000 non-null  object
 5   tenure_months                 20000 non-null  int64
 6   historical_spend              20000 non-null  float64
 7   recency_days                  20000 non-null  int64
 8   browsing_frequency            20000 non-null  int64
 9   avg_session_duration_sec      20000 non-null  float64
 10  cart_abandonment_rate         20000 non-null  float64
 11  support_tickets_count         20000 non-null  int64
 12  email_open_rate               20000 non-null  float64
 13  previous_discounts_accepted   20000 non-null  int64
 14  previous_purchases_12m        20000 non-null  int64
 15  avg_order_value               20000 non-null  float64
 16  website_visits_30d            20000 non-null  int64
 17  mobile_app_user               20000 non-null  int64
 18  loyalty_member                20000 non-null  int64
 19  subscription_status           20000 non-null  object
 20  preferred_channel             20000 non-null  object
 21  product_category              20000 non-null  object
 22  campaign_type                 20000 non-null  object
 23  day_of_week                   20000 non-null  object
 24  device_type                   20000 non-null  object
 25  competitor_price_index        20000 non-null  float64
 26  stock_availability            20000 non-null  object
 27  seasonality_index             20000 non-null  float64
 28  customer_satisfaction         20000 non-null  float64
 29  return_rate                   20000 non-null  float64
 30  days_since_last_campaign      20000 non-null  int64
 31  marketing_contact_count_30d   20000 non-null  int64
 32  discount_offered              20000 non-null  int64
 33  discount_amount               20000 non-null  float64
 34  purchased                     20000 non-null  int64
 35  basket_value_before_discount  20000 non-null  float64
 36  revenue                       20000 non-null  float64
 37  cost_of_goods                 20000 non-null  float64
 38  marketing_cost                20000 non-null  float64
 39  net_profit                    20000 non-null  float64
dtypes: float64(15), int64(15), object(10)
memory usage: 6.1+ MB

In [6]:
df.shape

(20000, 40)

In [7]:
df.dtypes

customer_id                       int64
age                               int64
income_bracket                   object
urbanicity                       object
region                           object
tenure_months                     int64
historical_spend                float64
recency_days                      int64
browsing_frequency                int64
avg_session_duration_sec        float64
cart_abandonment_rate           float64
support_tickets_count             int64
email_open_rate                 float64
previous_discounts_accepted       int64
previous_purchases_12m            int64
avg_order_value                 float64
website_visits_30d                int64
mobile_app_user                   int64
loyalty_member                    int64
subscription_status              object
preferred_channel                object
product_category                 object
campaign_type                    object
day_of_week                      object
device_type                      object
competitor_price_index          float64
stock_availability               object
seasonality_index               float64
customer_satisfaction           float64
return_rate                     float64
days_since_last_campaign          int64
marketing_contact_count_30d       int64
discount_offered                  int64
discount_amount                 float64
purchased                         int64
basket_value_before_discount    float64
revenue                         float64
cost_of_goods                   float64
marketing_cost                  float64
net_profit                      float64
dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

customer_id                     0
age                             0
income_bracket                  0
urbanicity                      0
region                          0
tenure_months                   0
historical_spend                0
recency_days                    0
browsing_frequency              0
avg_session_duration_sec        0
cart_abandonment_rate           0
support_tickets_count           0
email_open_rate                 0
previous_discounts_accepted     0
previous_purchases_12m          0
avg_order_value                 0
website_visits_30d              0
mobile_app_user                 0
loyalty_member                  0
subscription_status             0
preferred_channel               0
product_category                0
campaign_type                   0
day_of_week                     0
device_type                     0
competitor_price_index          0
stock_availability              0
seasonality_index               0
customer_satisfaction           0
return_rate                     0
days_since_last_campaign        0
marketing_contact_count_30d     0
discount_offered                0
discount_amount                 0
purchased                       0
basket_value_before_discount    0
revenue                         0
cost_of_goods                   0
marketing_cost                  0
net_profit                      0
dtype: int64

# Day 2:Data Quality Checks

In [13]:
df.describe()

,customer_id,age,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,cart_abandonment_rate,support_tickets_count,email_open_rate,...,days_since_last_campaign,marketing_contact_count_30d,discount_offered,discount_amount,purchased,basket_value_before_discount,revenue,cost_of_goods,marketing_cost,net_profit
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,110000.500000,36.231450,31.931350,4697.311133,33.938450,8.013700,225.596390,0.408680,1.100150,0.454065,...,27.539800,2.008950,8.750000,138.057008,0.284450,1580.251461,412.845859,271.286065,43.776133,97.783661
std,5773.647028,10.576232,19.621513,2103.322637,33.691309,2.790269,130.314799,0.194218,1.057155,0.195867,...,27.925974,1.429571,7.395285,161.234871,0.451163,965.740539,809.771617,534.537467,109.987695,254.100120
min,100001.000000,18.000000,1.000000,603.190000,0.000000,0.000000,10.000000,0.001000,0.000000,0.002000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,-791.900000
25%,105000.750000,28.000000,17.000000,3166.132500,9.000000,6.000000,130.300000,0.258000,0.000000,0.305000,...,8.000000,1.000000,3.750000,4.020000,0.000000,882.815000,0.000000,0.000000,1.500000,-4.500000
50%,110000.500000,36.000000,28.000000,4390.025000,23.000000,8.000000,201.750000,0.395000,1.000000,0.448000,...,19.000000,2.000000,7.500000,90.640000,0.000000,1371.180000,0.000000,0.000000,3.000000,-1.500000
75%,115000.250000,43.000000,43.000000,5876.940000,48.000000,10.000000,294.200000,0.548000,2.000000,0.598000,...,39.000000,3.000000,12.500000,195.025000,1.000000,2060.380000,546.897500,357.875000,7.500000,0.000000
max,120000.000000,75.000000,120.000000,19154.330000,180.000000,20.000000,1200.000000,0.977000,7.000000,0.969000,...,180.000000,11.000000,20.000000,1596.940000,1.000000,9652.160000,8204.620000,6154.590000,1596.940000,2937.120000

In [16]:
df["discount_offered"].value_counts().sort_index()

discount_offered
0     5000
5     5000
10    5000
20    5000
Name: count, dtype: int64

In [21]:
df["purchased"].value_counts( )

purchased
0    14311
1     5689
Name: count, dtype: int64

In [26]:
df.groupby("discount_offered")["purchased"].agg(["count", "mean"])

                  count    mean
discount_offered
0                  5000  0.2706
5                  5000  0.2822
10                 5000  0.2954
20                 5000  0.2896

# Day 3:Exploratory Data Analysis (EDA)

# Day 4:Data Preprocessing